[package]
name = "portal-solutions-asm-regalloc"
version = "0.1.0"
edition = "2024"
license.workspace = true
description.workspace = true

[dependencies]
portal-pc-asm-common.workspace = true
typeid.workspace = true

[features]
alloc=[]
regalloc-integration=[]